### ISSUE TITLE
broken links in Advanced Python section

### ISSUE THREAD

**Issue by thanushipeiris** [MonashBioinformaticsPlatform/learning-resource-links#1]
The first two links in the [Advanced Python](https://github.com/MonashBioinformaticsPlatform/learning-resource-links#advanced-python) section no longer point to valid URLs FYI.

Perhaps consider archiving links using the [wayback machine](https://archive.org/web/) and then pointing to the wayback archived URL (this is what Wikipedia does/is moving towards) (e.g. see this link on [kidneys](https://web.archive.org/web/20080210070807/http://www.bioportfolio.com/indepth/Kidney.html)).

Great resource though! Just came across it but looks super useful, thank you for compiling.

**Comment by pansapiens** [comment]
Thanks - I've changed these to point to the archive.org versions.
